import { Inter } from 'next/font/google'
import './globals.css'
import { ThirdwebProvider } from '@/components/ThirdwebProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Maker20',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full bg-black`} >
        <ThirdwebProvider 
          activeChain="ethereum"
          clientId="13f67df54a3a7c396e1167c2d49cd99f"s>
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  )
}
